### ISSUE TITLE
Cell Profiler in Jupyter Notebook

### ISSUE THREAD

**Issue by hhelmbre** [CellProfiler/core#12]
Hi!

I have been trying to get Cell Profiler to work in Jupyter Notebooks off an on for a few weeks now (it would seriously increase the speed of our cell morphology pipeline if it were in a notebook and not using the desktop version). I *really really* want it to work because I am a big fan of the desktop version.

**So first question:** Do you have a working tutorial for using the current version of Cell Profiler in Jupyter notebooks?

**If not, my current issue:** I am using the examples from CellProfiler/notebooks/cellprofiler_demo.ipynb (I am aware they are slightly outdated but they were the best I could find). I fixed the module imports to be cellprofiler_core instead of cellprofiler as in the example, but now I am hitting the error shown in the attached file. 

<img width="1227" alt="Screen Shot 2020-06-15 at 11 30 59 AM" src="https://user-images.githubusercontent.com/46461897/84693067-baaac700-aefb-11ea-94a5-1aa25270dc04.png">

Does anyone know how to proceed? Is the JavaException error independent of the ERROR:root:Failed to load pipeline errors for _pipeline.py, _module.py, and metatdata.py?

I hope that was informative enough.  Thank you!

**Comment by DavidStirling** [comment]
Hi, thanks for getting in touch!

CellProfiler 4 is still in development, we'll be updating the tutorials when it's released but for now I'm afraid they're outdated.

I'm aware of the issue you describe, it's related to pipeline decoding. Hopefully it was fixed in cellprofiler-core RC7. Would you be able to confirm which version you currently have, and if you're on the latest would you be able to upload a copy of the problem pipeline? Thanks

**Comment by 0x00b1** [comment]
Yep, @DavidStirling is correct about the underlying issue. Upgrade to the latest and you should be good. I’ll add that I run CellProfiler from a Jupyter Notebook nearly everyday. Running pipelines is a snap. Editing is still cumbersome, but not too bad.

**Comment by hhelmbre** [comment]
Thanks so much for your response! Its good to know that it is working in Jupyter notebooks - gives me the energy to keep working on it. 

i updated to cellprofiler-core RC7 and I switched to using the Example Human Cell pipeline from the cellprofiler website. These two changes (update and pipeline switch) got rid of all the errors except the JavaException. Any ideas on what could be causing that issue?

**Comment by 0x00b1** [comment]
@hhelmbre the Java exceptions should be resolved with the next RC. Let us know!

**Comment by hhelmbre** [comment]
Ooh exciting! I will add it to my to do list to give it a try :) :) Thank you!
