### ISSUE TITLE
Request new release of cellprofiler-core

### ISSUE THREAD

**Issue by GenevieveBuckley** [CellProfiler/core#71]
The main CellProfiler repository has [pinned cellprofiler-core==4.0.7](https://github.com/CellProfiler/CellProfiler/blob/efb4cc3bae49807752013c1f733a099e2806f6c4/setup.py#L66) but relies on functions only available from the cellprofiler-core master branch.

I propose making a new release of cellprofiler-core, and then bumping the version pinned in the main CellProfiler setup.py

Context: https://github.com/CellProfiler/CellProfiler/issues/4346#issuecomment-777163258

This isn't a blocking problem for me (I've just installed both CellProfiler and cellprofiler-core from their master branches), more a friendly heads-up that you'll probably see this pop up in the future :smile:

**Comment by DavidStirling** [comment]
This should be addressed by #67 and cellprofiler/cellprofiler#4348, we're about to release this update.

**Comment by GenevieveBuckley** [comment]
Oh great, thanks for letting me know!

**Comment by DavidStirling** [comment]
v4.1.3 is now out!
